export const ERROR_NOTIFICATION = "ERROR_NOTIFICATION";
export const INFO_NOTIFICATION = "INFO_NOTIFICATION";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";

export const ADD_TO_FAVOURITES = "ADD_TO_FAVOURITES";
export const REMOVE_FROM_FAVOURITES = "REMOVE_FROM_FAVOURITES";

export const GET_ARTICLES = "GET_ARTICLES";
export const ADD_ABSTRACT = "ADD_ABSTRACT";

export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
